
format = "$directory$character"
right_format = """$cmd_duration$git_branch"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [](#ffffff)"
error_symbol = " [](#df5b61)"
vicmd_symbol = "[  ](#78b892)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:#0d0d0d bg:none)[$duration]($style)[](fg:#0d0d0d bg:#0d0d0d)[](fg:#ffffff bg:#0d0d0d)[](fg:#1c252c bg:#ffffff)[](fg:#ffffff bg:none) "
disabled = false
style = "fg:#d9d7d6 bg:#0d0d0d"

[directory]
format = "[](fg:#0d0d0d bg:none)[$path]($style)[](fg:#0d0d0d bg:#0d0d0d)[](fg:#ffffff bg:#0d0d0d)[](fg:#1c252c bg:#ffffff)[](fg:#ffffff bg:none)"
style = "fg:#d9d7d6 bg:#0d0d0d"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:#0d0d0d bg:none)[$branch]($style)[](fg:#0d0d0d bg:#0d0d0d)[](fg:#ffffff bg:#0d0d0d)[](fg:#282c34 bg:#ffffff)[](fg:#ffffff bg:none) "
style = "fg:#d9d7d6 bg:#0d0d0d"
